/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-1",
    "aws_cloud_logic_custom": [
        {
            "name": "apic6cb0264",
            "endpoint": "https://tf61vtb5uc.execute-api.us-west-1.amazonaws.com/staging",
            "region": "us-west-1"
        },
        {
            "name": "apid6755dce",
            "endpoint": "https://hia57mzxu0.execute-api.us-west-1.amazonaws.com/staging",
            "region": "us-west-1"
        },
        {
            "name": "test",
            "endpoint": "https://6gda44vim3.execute-api.us-west-1.amazonaws.com/staging",
            "region": "us-west-1"
        },
        {
            "name": "apid239f9ea",
            "endpoint": "https://g9odeats82.execute-api.us-west-1.amazonaws.com/staging",
            "region": "us-west-1"
        }
    ]
};


export default awsmobile;
